### ISSUE TITLE
testing module seems to only have one `request` method

### ISSUE THREAD

**Issue by Tronikelis** [thruster-rs/Thruster#251]
Hey, I wanted to try writing simple tests.

The readme says:
```rust
let mut app = App::<Request, Ctx, ()>::new_basic();

...

app.get("/plaintext", m![plaintext]);

...

let result = testing::get(app, "/plaintext");

assert!(result.body == "Hello, World!");
```

But on thruster `1.3.3` with the hyper server the `testing::get` doesn't seem to get exported. Take a look at my example:

`main.rs`
```rust
use thruster::{m, middleware_fn, testing};
use thruster::{App, BasicContext as Ctx, HyperRequest};
use thruster::{MiddlewareNext, MiddlewareResult};

#[middleware_fn]
async fn plaintext(mut context: Ctx, _next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
    let val = "Hello, World!";
    context.body(val);
    Ok(context)
}

fn main() {
    let app = App::<HyperRequest, Ctx, ()>::new_basic().get("/plaintext", m![plaintext]);
    let result = testing::get(app, "/plaintext");
}
```

`Cargo.toml`:
```toml
[package]
name = "thruster-testing-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thruster = { version = "1.3.3", features = ["hyper_server"] }
tokio = { version = "1.28.1", features = ["full"] }
```

`cargo build`:
```
error[E0425]: cannot find function `get` in module `testing`
  --> src\main.rs:14:27
   |
14 |     let result = testing::get(app, "/plaintext");
   |                           ^^^ not found in `testing`

```

It works without the `hyper_server` feature enabled though
